# Generated by Django 5.1.1 on 2024-10-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_reserve_is_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='players_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
