# Generated by Django 5.1.1 on 2024-10-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_reserve_players_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
