# Generated by Django 5.1.1 on 2024-10-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0010_alter_reserve_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
