# Generated by Django 5.1.1 on 2024-10-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0011_alter_reserve_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
        ),
    ]
