# Generated by Django 5.1.1 on 2024-10-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0012_snack'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='reserve_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
