# Generated by Django 5.1.1 on 2024-10-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0013_snack_reserve_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='reserve_id',
        ),
    ]
