# Generated by Django 5.1.1 on 2024-10-07 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0014_remove_snack_reserve_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnackOnReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authy.reserve')),
                ('snack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authy.snack')),
            ],
        ),
    ]
